version: "3"

services:

  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"


  vote:
    build: ./vote/
    ports:
      - 5000:80


  result:
    build: ./result/
    ports:  # corrected 'port' to 'ports'
      - 5001:80 

      
  worker:
    build: ./worker/
